name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: cp package.json ./lib/
      - run: cp README.md ./lib/
      - run: cp LICENSE ./lib/
      - run: npm publish ./lib/ --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
